name: test
on:
  push:
    branches:
      - "main"
      - "master"
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [18, 20, 22, 24]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Upgrade npm for Node 14
        if: matrix.node == 14
        run: npm i -g npm@8

      - name: npm ci
        run: npm ci --ignore-scripts

      - name: test
        run: |
          case "${{ matrix.node }}" in "24")
            npm run test:coverage
          ;;*)
          npm test
          ;;
          esac

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: npm ci
        run: npm ci --ignore-scripts

      - name: build
        run: npm run build

      - name: lint
        run: npm run lint

      - name: typecheck
        run: npm run typecheck
